### PR TITLE
Set up Resources section

### PR DESCRIPTION
**Pull request by Dindihub**
@chalin Created a new resources PR to solve commit issues in  PR #12 

The deploy preview from tufresources link is more accurate for this branch.  Please review. Thanks

### CODE REVIEW

**Comment by Dindihub** [comment]
@chalin I've addressed your comments from #12. I'm ready to close this one and move to the other issues upon your approval. Thanks

**Comment by lukpueh** [comment]
> The deploy preview from tufresources link is more accurate for this branch.

Out of curiosity, why are there two deployment previews?

**Review by lukpueh — APPROVED** [review]
Looks great! 

Can I ask you a favor? Would you mind clicking all links that you added in this PR, which, I suppose, you copied  from theupdateframework.io, and list the ones that don't work in a new issue in the upstream repo? --> https://github.com/theupdateframework/theupdateframework.io/issues

**Comment by Dindihub** [comment]
> > The deploy preview from tufresources link is more accurate for this branch.
> 
> Out of curiosity, why are there two deployment previews?

My mistake. I was having trouble configuring the Netlify build on the main branch so I added the preview to this branch too. But I'll delete it to avoid confusion.

**Comment by Dindihub** [comment]
> Looks great!
> 
> Can I ask you a favor? Would you mind clicking all links that you added in this PR, which, I suppose, you copied from theupdateframework.io, and list the ones that don't work in a new issue in the upstream repo? --> https://github.com/theupdateframework/theupdateframework.io/issues

Sure. No problem. And thanks for the review.

**Pull request merged**
